language: php
php:
    - 5.2
    - 5.3
    - 5.4
compiler:
    - gcc
    - clang
before_script:
    - sudo apt-get install libgtest-dev swig
    - cd /usr/src/gtest; sudo cmake .; sudo make; sudo mv libg* /usr/lib/
script: scons test

