language: php
php:
    - 5.2
    - 5.3
    - 5.4
compiler:
    - gcc
    - clang
before_script:
    - sudo ln -sf /opt/phpfarm/inst/bin/php-config-* /usr/bin/php-config
    - sudo apt-get install libgtest-dev
script: scons test

