language: php
php:
    - 5.2
    - 5.3
    - 5.4
compiler:
    - gcc
    - clang
env:
    - PATH=/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin:$PATH
before_script:
    #    - sudo ln -sf /opt/phpfarm/inst/bin/php-config-* /usr/bin/php-config
    - sudo apt-get install libgtest-dev
    - echo $PATH
script: scons test

