language: php
php:
    - 5.2
    - 5.3
    - 5.4
before_script:
    - sudo apt-get install libgtest-dev swig
    - cd /usr/src/gtest; sudo cmake .; sudo make; sudo mv libg* /usr/lib/; cd -
env:
    - CC=gcc CXX=g++
    - CC=clang CXX=clang++
script: scons test && sudo scons install && sudo scons install-php

